server:
  port: 8181
  spring:
    application:
      name: UserServiceApplication
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka